source 'https://rubygems.org'
ruby '2.0.0'
#ruby-gemset=railstutorial_rails_4_0

gem 'rails', '4.1.1'
gem 'bootstrap-sass', '2.3.2.0'
gem 'bcrypt-ruby', '3.1.2'

group :development do
  gem 'sqlite3', '1.3.8'
end

gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'private_pub'
gem 'thin'
gem 'gemoji'

group :doc do
  gem 'sdoc', '~> 0.4.0', require: false
end

group :production do
  gem 'rails_12factor'
  gem 'pg', '0.18.4'
end
